cluster:
  extraManifests:
    - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/v0.9.3/deploy/standalone-install.yaml
    - https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.8.1/components.yaml
  etcd:
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
  scheduler:
    extraArgs:
        bind-address: 0.0.0.0
  proxy:
    extraArgs:
      metrics-bind-address: 0.0.0.0:10249
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0
